name: Publish 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

     # Install Landscape2 
      - name: Install Landscape2
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cncf/landscape2/releases/download/v0.8.1/landscape2-installer.sh | sh

     # Build Landscape
      - name: Build Landscape
        run: |
          landscape2 build \
            --data-file data.yml \
            --settings-file settings.yml \
            --guide-file guide.yml \
            --logos-path logos \
            --output-dir build

      - name: Deploying to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build --project-name=landscapes
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
